window.vvGet=async e=>(new DOMParser).parseFromString(await(await fetch(e,{credentials:"include"})).text(),"text/html");window.vvT=(e,t)=>e.querySelector(t)?.textContent.replace(/\s+/g," ").trim()||"";window.vvNum=e=>+String(e??"").replace(/\s/g,"").replace(",",".")||null;window.vvSave=(e,t)=>{try{sessionStorage.setItem("vv_"+e,JSON.stringify(t))}catch(e){}return t};window.vvLoad=e=>{try{
return JSON.parse(sessionStorage.getItem("vv_"+e))}catch(e){return null}};window.headerInfo=()=>(document.querySelector("header")?.innerText||"").replace(/\s+/g," ").slice(0,120);window.loadLazy=e=>{const t=document.querySelector(`.js-section-block-lazy._ni[data-code="${e}"]`);if(!t||!window.jQuery)return false;const a=t.dataset.func
;const r=a&&typeof window[a]==="function"?window[a]:typeof window.updateLazyItems==="function"?window.updateLazyItems:null;if(!r)return false;t.classList.remove("_ni");try{r(jQuery(t))}catch(e){t.classList.add("_ni");return false}return true};window.lazyWarn=(e,t)=>{const a=vvLoad("lazyWarn")||{};if(t)a[e]={msg:t,t:Date.now()};else delete a[e];return vvSave("lazyWarn",a)}
;window.lazyWarnings=()=>Object.entries(vvLoad("lazyWarn")||{}).filter(([,e])=>Date.now()-e.t<20*6e4).map(([e,t])=>`${e}: ${t.msg}`);window.greenEmpty=()=>{const e=document.querySelector("#js-Delivery__Order-green-state-empty");return!!e&&!e.classList.contains("hidden")};window.waitGreen=async(e=1e4)=>{const t=Date.now();while(Date.now()-t<e){
if(document.querySelector('[data-is-green="Y"]')||greenEmpty())break;await new Promise(e=>setTimeout(e,500))}return document.querySelectorAll('[data-is-green="Y"]').length};window.readGreen=()=>{const e=new Set;return vvSave("green",[...document.querySelectorAll('[data-is-green="Y"]')].filter(t=>t.dataset.productId&&!e.has(t.dataset.productId)&&e.add(t.dataset.productId)).map(e=>{
const t=e.closest(".ProductCard")||e.parentElement;const a=t.querySelector('a[href*="/goods/"]');const r=e=>(t.querySelector(e)?.textContent||"").replace(/\s/g,"");return{id:e.dataset.productId,name:[(t.querySelector("a[title]")?.getAttribute("title")||a?.textContent||"").replace(/&nbsp;/g," ").replace(/\s+/g," ").trim()].map(e=>{
const a=(t.querySelector(".ProductCard__linkWeight")?.textContent||"").replace(/\s+/g," ").trim();return a&&!e.endsWith(a)?e+", "+a:e})[0],href:(a?.getAttribute("href")||"").split("?")[0],price:vvNum(r(".js-datalayer-catalog-list-price")),old:vvNum(r(".js-datalayer-catalog-list-price-old")),unit:/\/кг/.test(t.querySelector(".Price")?.textContent||"")?"кг":"шт",max:e.dataset.max}}))}
;window.couponsText=async()=>{const e=await vvGet("/cart/");const t=(e.body.textContent||"").replace(/\s+/g," ");if(/Купонов пока нет/.test(t))return vvSave("coupons","Купонов пока нет");const a=[...e.querySelectorAll('[class*="oupon"], [class*="upon"]')].find(e=>/купон/i.test(e.textContent))
;return vvSave("coupons",a?a.textContent.replace(/\s+/g," ").trim().slice(0,600):"блок купонов не найден — проверить руками")};window.readBasket=async()=>{const e=await(await fetch("/cart/",{credentials:"include"})).text();const t=e.match(/basketPageData\s*=\s*JSON\.parse\('((?:[^'\\]|\\.)*)'\)/);if(!t)return null;const a=JSON.parse(JSON.parse('"'+t[1].replace(/\\'/g,"'")+'"'))
;const r=Array.isArray(a.basket)?a.basket:Object.values(a.basket||{});return r.map(e=>({id:String(e.PRODUCT_ID??""),q:+(e.Q??e.QUANTITY)||1,name:e.NAME??"",price:e.PRICE,base:e.BASE_PRICE,diff:e.DIFF_PRICE,green:!!+e.IS_GREEN,lp:e.IS_LP==="Y",label:e.PRICE_LABEL}))};window.cartSnapshot=async()=>{window.__cart0=await readBasket();vvSave("cart0",__cart0)
;return __cart0?`${__cart0.length} позиций`+(__cart0.length?": "+__cart0.map(e=>`${e.name.slice(0,30)} ×${e.q} по ${e.price}`+(e.diff?` (−${e.diff})`:"")).join("; "):""):"basketPageData не найден"};window.cartDiff=async()=>{const e=await readBasket();if(!window.__cart0)window.__cart0=vvLoad("cart0");if(!e||!window.__cart0)return"нет снимка или basketPageData";const t=e=>e.id+"×"+e.q
;const a=new Set(__cart0.map(t)),r=new Set(e.map(t));return{same:a.size===r.size&&[...a].every(e=>r.has(e)),added:e.filter(e=>!a.has(t(e))).map(e=>e.name),removed:__cart0.filter(e=>!r.has(t(e))).map(e=>e.name)}};window.cartSixPlaces=()=>{if(!window.__cart0)window.__cart0=vvLoad("cart0");if(!window.__sets)window.__sets=vvLoad("sets");if(!__cart0||!__sets)return null
;return __cart0.filter(e=>__sets.flat().some(t=>t.href.includes("-"+e.id+"/"))).map(e=>e.name)};window.cartStep=async()=>{const e=loadLazy("cart_green_labels");const t=await waitGreen();const a=vvSave("greenState",t?"loaded":greenEmpty()?"empty":"unknown")
;if(a==="unknown")lazyWarn("cart_green_labels",e?"функция сайта не загрузила блок":"заглушка или функция загрузки не найдены");else if(e)lazyWarn("cart_green_labels",null);return{width:innerWidth,header:headerInfo(),green:readGreen().length,greenState:a,lazy:e,coupons:await couponsText(),cart:await cartSnapshot()}};window.vvFingerprint=e=>{
const t=e=>typeof e==="function"||e instanceof RegExp?String(e):Array.isArray(e)?"["+e.map(t).join(",")+"]":e&&typeof e==="object"?"{"+Object.keys(e).sort().map(a=>a+":"+t(e[a])).join(",")+"}":JSON.stringify(e);const a=e.map(e=>e+"="+t(window[e])).join(";").replace(/\s+/g," ");let r=2166136261;for(let e=0;e<a.length;e++){r^=a.charCodeAt(e);r=Math.imul(r,16777619)>>>0}return r.toString(16)}
;window.vvCheckCart=()=>["vvGet","vvT","vvNum","vvSave","vvLoad","headerInfo","loadLazy","lazyWarn","lazyWarnings","greenEmpty","waitGreen","readGreen","couponsText","readBasket","cartSnapshot","cartDiff","cartSixPlaces","cartStep","vvFingerprint"].filter(e=>typeof window[e]!=="function");
'vkusvill cart-kit loaded, missing: ' + JSON.stringify(vvCheckCart()) + ', check: ' + (vvFingerprint(["vvGet", "vvT", "vvNum", "vvSave", "vvLoad", "headerInfo", "loadLazy", "lazyWarn", "lazyWarnings", "greenEmpty", "waitGreen", "readGreen", "couponsText", "readBasket", "cartSnapshot", "cartDiff", "cartSixPlaces", "cartStep", "vvFingerprint"]) === '7ac21fe0' ? 'ok' : 'ИСКАЖЁН');
